name: Buildx Build Docker image

on:
  push:

jobs:
  build:
    name: Buildx build image

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: |
          ./buildx.sh

      - name: Check images
        run: |
          ls
